Repository PRX/theworld.org, pull requests merged in 2021-11, with the labels that each got.

#247 #246: Update default header label of latest stories sidebar block
  components/Sidebar/SidebarLatestStories/SidebarLatestStories.tsx
  components/pages/Homepage/Homepage.tsx
Labels: Passes Code Review

#253 #249 a11y score back to 100
  components/AppCtaBanner/AppCtaBanner.tsx
  components/AppCtaLoadUnder/AppCtaLoadUnder.tsx
  components/AppHeader/AppHeaderNav/AppHeaderNav.tsx
Labels: Passes Code Review

#252 #251: Prevent feature header content form being clipped on short screens
  components/pages/Story/layouts/feature/components/StoryHeader/StoryHeader.feature.styles.ts
Labels: Passes Functional Review, Passes Code Review

#267 HOTFIX: Logic for filling in featured stories arrays
  lib/fetch/category/fetchCategory.ts
  lib/fetch/category/fetchCategoryStories.ts
  lib/fetch/program/fetchProgram.ts
  lib/fetch/program/fetchProgramEpisodes.ts
  lib/fetch/program/fetchProgramStories.ts
  lib/fetch/term/fetchTerm.ts
  lib/fetch/term/fetchTermEpisodes.ts
  lib/fetch/term/fetchTermStories.ts
  pages/api/category/[id]/index.ts
  pages/api/category/[id]/stories/[page].ts
  pages/api/program/[id]/episodes/[page].ts
  pages/api/program/[id]/index.ts
  pages/api/program/[id]/stories/[page].ts
  pages/api/term/[id]/episodes/[page].ts
  pages/api/term/[id]/index.ts
  pages/api/term/[id]/stories/[page].ts
Labels: Passes Functional Review

#269 HOTFIX: Try hashing static props data
  package.json
  pages/[...alias].tsx
  pages/index.tsx
  pages/media/[...slug].tsx
  yarn.lock
Labels: Passes Functional Review

#285 #284: Handle province term paths
  amplify.yml
  components/AppCtaBanner/AppCtaBanner.tsx
  components/AppCtaLoadUnder/AppCtaLoadUnder.tsx
  components/Sidebar/SidebarCta/SidebarCta.styles.ts
  components/pages/Term/Term.tsx
  jest.config.js
  lib/fetch/term/fetchTerm.ts
  lib/fetch/term/fetchTermStories.spec.ts
  lib/fetch/term/fetchTermStories.ts
Labels: Passes Functional Review
